### PR TITLE
added cabbar.org

### PR DESCRIPTION
**Pull request by askin**
i added cabbar.org to list

### CODE REVIEW

**Comment by stpeter** [comment]
All the text in the server description runs together - perhaps add some spaces between the words? ;-)

**Comment by stpeter** [comment]
Email verification sent to the canonical addresses for the cabbar.org domain.

**Comment by stpeter** [comment]
Having not heard from the administrators, I'm closing this PR. It can be opened again if there is further activity.

**Comment by askin** [comment]
Hi, I terminated the service.

**Comment by stpeter** [comment]
OK, thanks for letting us know. You probably mentioned it somewhere else too and I missed it. :(

**Pull request closed without merging**
