### PR TITLE
Create 0101010.one.xml

### PR DESCRIPTION
**Pull request by alexh-name**

### CODE REVIEW

**Comment by stpeter** [comment]
Verification email sent 2016-06-05.

BTW https://github.com/stpeter/xmppdotnet/pull/53/files lists your HTTPS server as https://0101010.ones/ but think you have the TLD wrong there (should be .one, not .ones).

**Comment by stpeter** [comment]
<hostmaster@0101010.one>: host 0101010.one[95.143.172.232] said: 554 Refused.
    Sending to remote addresses (relaying) is not allowed. (in reply to RCPT TO
    command)

<postmaster@0101010.one>: host 0101010.one[95.143.172.232] said: 554 Refused.
    Sending to remote addresses (relaying) is not allowed. (in reply to RCPT TO
    command)

<webmaster@0101010.one>: host 0101010.one[95.143.172.232] said: 554 Refused.
    Sending to remote addresses (relaying) is not allowed. (in reply to RCPT TO
    command)

**Comment by alexh-name** [comment]
I'm sorry for the sloppiness. I corrected the errors now.

**Comment by stpeter** [comment]
If you are still interested, please file a pull request at https://invent.kde.org/melvo/xmpp-providers so that your server will be added to the new list at https://providers.xmpp.net/

**Pull request closed without merging**
