### PR TITLE
Added yax.im service

### PR DESCRIPTION
**Pull request by ge0rg**

### CODE REVIEW

**Comment by stpeter** [comment]
Verification request sent to canonical addresses for the yax.im domain.

**Comment by ge0rg** [comment]
Whoops, I just realized there was an error in the MX DNS entry. As the wrong entry's TTL was 24h, I'd kindly ask you to re-try tomorrow or to flush your resolver cache. The correct MX is bender.boerde.de, not bender.boerde.de.yax.im ;-)

**Comment by stpeter** [comment]
Resent but delivery failed. Will try again tonight.

**Comment by stpeter** [comment]
Still getting delivery failed:

554 5.7.1 <hostmaster@yax.im>: Relay access denied

**Comment by ge0rg** [comment]
Whoops. Had to explicitly add the domain on the MTA, just adding virtual entries was not sufficient. Should be working now.

**Comment by stpeter** [comment]
Resent. :-)

**Comment by stpeter** [comment]
Verified!

**Pull request merged**
