### PR TITLE
Add jabber.chaos-darmstadt.de

### PR DESCRIPTION
**Pull request by azrdev**

### CODE REVIEW

**Comment by stpeter** [comment]
Verification email sent.

**Comment by mweinelt** [comment]
Hi, we've received your verification mail with `Message-ID: <5694628D.2080303@stpeter.im>` and gladly approve.

Unfortunately our mail server is currently wrongfully listed as having a Dynamic IP Address by SORBS. We are currently trying to rectify this.

```
<...@stpeter.im>: host mailhost.stpeter.im[207.210.219.225] said: 554 5.7.1
    Service unavailable; Client host [130.83.177.130] blocked using
    dul.dnsbl.sorbs.net; Dynamic IP Addresses See:
    http://www.sorbs.net/lookup.shtml?130.83.177.130 (in reply to RCPT TO
    command)
```

**Comment by azrdev** [comment]
@stpeter do we still have to do anything to get included? The SORBS listing should be long resolved.

**Comment by tfar** [comment]
@azrdev  just send another verification mail to the host admins of chaos-darmstadt.de. As soon as I get a response I'll proceed with this PR.

**Comment by tfar** [comment]
Received verification.

**Pull request merged**
