### PR TITLE
new vcard

### PR DESCRIPTION
**Pull request by Kernel-Error**
add vcard of my service

### CODE REVIEW

**Comment by tfar** [comment]
Send verification mail.

**Comment by Kernel-Error** [comment]
Received :-)

Am 29. Juni 2016 18:44:16 MESZ, schrieb T Markmann <notifications@github.com>:
>Send verification mail.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/stpeter/xmppdotnet/pull/79#issuecomment-229416003

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tfar** [comment]
@Kernel-Error Could you please reply to the verification mail.

**Comment by tfar** [comment]
Verification received.

**Pull request merged**
