### PR TITLE
Adding fysh.in vcard

### PR DESCRIPTION
**Pull request by fysh-xmpp**
Please accept to add fysh.in to the list of XMPP servers

### CODE REVIEW

**Comment by stpeter** [comment]
Verification message sent to the canonical email addresses for fysh.in.

**Comment by stpeter** [comment]
As far as I can see, I have not received a reply to the verification message.

**Comment by fysh-xmpp** [comment]
Could you confirm which email you sent it to? I haven't received anything at ```admin@fysh.in``` which is on the whois records.

**Comment by stpeter** [comment]
Resent to the address found in whois. Sorry about the delay.

**Comment by stpeter** [comment]
Acknowledgement received. Adding this server now.

**Pull request merged**
