### PR TITLE
Add vcard for decent.im

### PR DESCRIPTION
**Pull request by andrey-utkin**
Please let me know if any info is incorrect or required info is missing.

Please also elaborate how email on the domain is checked. I don't have email configured very well at the moment.

### CODE REVIEW

**Comment by andrey-utkin** [comment]
Email receival on xmpp@decent.im has been configured. Please kindly proceed with verification.

**Comment by andrey-utkin** [comment]
Anybody?

**Comment by stpeter** [comment]
Email verification sent to hostmaster, postmaster, and webmaster @ decent.im.

**Comment by andrey-utkin** [comment]
Sorry but at the time of previous verification email the service was undergoing migration to different distro and email server wasn't set up. Resend verification please (hostmaster, postmaster, and webmaster @ decent.im are listened now). Thank you.

**Comment by andrey-utkin** [comment]
Up.

**Comment by stpeter** [comment]
If you are still interested, please file a pull request at https://invent.kde.org/melvo/xmpp-providers so that your server will be added to the new list at https://providers.xmpp.net/

**Pull request closed without merging**
