### PR TITLE
Add patchcord.be server

### PR DESCRIPTION
**Pull request by drixter**
Add patchcord.be server

### CODE REVIEW

**Comment by drixter** [comment]
Any update?

**Comment by tfar** [comment]
The filename should be `patchcord.be.xml`.

**Comment by drixter** [comment]
Done.

**Comment by tfar** [comment]
Looking at the list of information to provide on https://xmpp.net/register.php your vcard is missing some of these.

**Comment by drixter** [comment]
Fixed. Should be now OK.

**Comment by tfar** [comment]
Send verification mail.

**Comment by drixter** [comment]
Confirm

Wysłano ze smartfonu Sony Xperia™

---- Użytkownik T Markmann napisał ----


Send verification mail.

**Pull request merged**
