### PR TITLE
Please add xmpp.is

### PR DESCRIPTION
**Pull request by Lunarrr**

### CODE REVIEW

**Comment by stpeter** [comment]
Verification message sent to the canonical email addresses for xmpp.is.

**Comment by Lunarrr** [comment]
Did you email lunar@xmpp.is ?

That is my XMPP and that email doesn't exist but admin@xmpp.is is the main email. Can you resend it there?

**Comment by stpeter** [comment]
I just resent the verification message to one of the email addresses that I found in the whois record.

**Comment by Lunarrr** [comment]
Okay, I've replied to your email.

**Comment by stpeter** [comment]
Reply received! Sorry about the delayed processing.

**Pull request merged**
