### PR TITLE
Add gnu.gr server

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@tfar have you sent us a verification email? Could you please resend since we didn't get it. We use the hostmaster@ address.

Thanks

**Comment by comzeradd** [comment]
Hey @tfar any update on this?

**Comment by tfar** [comment]
Currently there's little motivation working on this pull requests, until #89 is fixed. If the merges here don't affect the output seen on the website, there's not much value to it. When that is fixed, I'll continue to process the PRs.

**Comment by stpeter** [comment]
If you are still interested, please file a pull request at https://invent.kde.org/melvo/xmpp-providers so that your server will be added to the new list at https://providers.xmpp.net/

**Pull request closed without merging**
