### PR TITLE
Create xmpp.dk.vcard

### PR DESCRIPTION
**Pull request by graffen**

### CODE REVIEW

**Comment by tfar** [comment]
Send verification mail.

**Comment by graffen** [comment]
@tfar Wow, sorry, I just noticed this. It seems I never received the verification mail (or it ended up in my spam folder and I didn't see it). Can you please re-send?

**Comment by graffen** [comment]
@tfar did you resend the verification mail by any chance?

**Comment by stpeter** [comment]
If you are still interested, please file a pull request at https://invent.kde.org/melvo/xmpp-providers so that your server will be added to the new list at https://providers.xmpp.net/

**Pull request closed without merging**
