### PR TITLE
add domain psjb.me

### PR DESCRIPTION
**Pull request by psjbeisler**
Please add my public XMPP service to the list at xmpp.net.

### CODE REVIEW

**Comment by stpeter** [comment]
Email verification sent to hostmaster/postmaster/webmaster @ psjb.me. Delivery failed to all three addresses.

**Comment by psjbeisler** [comment]
none of those are valid emails for me that why

**Comment by stpeter** [comment]
See http://tools.ietf.org/html/rfc2142 and https://xmpp.net/verify.php - we use those email addresses to verify control over the domain.

**Comment by stpeter** [comment]
However, I see that the whois record has another address so I will try that.

**Comment by stpeter** [comment]
Verification received. :-)

**Pull request merged**
